//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanDetay
    {
        public IlanDetay()
        {
            this.Ilan = new HashSet<Ilan>();
        }
    
        public int Id { get; set; }
        public string Kat { get; set; }
        public string OdaSayi { get; set; }
        public string BanyoSayi { get; set; }
        public string Isitma { get; set; }
        public string Esyalimi { get; set; }
        public string Aciklama { get; set; }
        public string Adres { get; set; }
    
        public virtual ICollection<Ilan> Ilan { get; set; }
    }
}
